# Generated by Django 4.0.1 on 2022-02-01 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='card',
            name='column',
        ),
        migrations.RemoveField(
            model_name='columns',
            name='kanban',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='kanban',
        ),
        migrations.RemoveField(
            model_name='column',
            name='board',
        ),
        migrations.AddField(
            model_name='column',
            name='kanban',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='board.kanban'),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Columns',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='kanban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.column'),
        ),
        migrations.AlterField(
            model_name='note',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.task'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.task'),
        ),
    ]
