# Generated by Django 4.0.1 on 2022-02-09 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanban',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kanban',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanbans', to=settings.AUTH_USER_MODEL),
        ),
    ]
