# Generated by Django 4.0.1 on 2022-02-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='index',
        ),
    ]
