# Generated by Django 4.0.1 on 2022-02-09 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanban',
            old_name='created_by',
            new_name='user',
        ),
    ]
