# Generated by Django 4.0.1 on 2022-02-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_kanban_description_alter_kanban_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanban',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
