# Generated by Django 4.0.1 on 2022-02-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_card_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
